### ISSUE TITLE
Seccion Servicios

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#21]
Estructura base la seccion, componentes, datos
https://www.notion.so/Seccion-Servicios-398b1af4a6c649d097db12237fe183da?pvs=4

Elementos posbilemente necesarios

- wrapper de seccion con id
- card service
- card service detailed

TODO: (v2 services sections) diseño final, transiciones, animaciones, resto que fuere necesario.

**Comment by Roxha-V** [comment]
Se resuelve v2 - section services
