### ISSUE TITLE
Small devices - Hero slider overlaps menu

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#22]
![chrome-capture-2024-5-3 (2)](https://github.com/Roxha-V/PTGA-Landing/assets/87544205/f895b1a5-7742-41bc-acbe-6fd76f4ae43e)

**Comment by Roxha-V** [comment]
Resolved issue 21 -  in branch 18 - Ready for review @devPalta

**Comment by Roxha-V** [comment]
The Hero slider no longer overlaps the drawer menu. The style of the drawer is changed, correctly adjusting the order of the component layers

**Comment by Roxha-V** [comment]
@devPalta i tried to do a pull request , but it seems that develop branch  and 22_small_devices_hero_slider_overlaps_menu branch are identical. Idk why, i think i had made the change (wrongly) in other branch before you create this issue and probably we merge that one with develop. Can we check together in the review reunion?

**Comment by devPalter** [comment]
se estima 3hs
