### ISSUE TITLE
Improvement - navbar menu

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#28]
make sticky functionallity

**Comment by devPalter** [comment]
se estiman 6 / 8 hs

**Comment by Roxha-V** [comment]
Branch 28 was created from the main branch (and not from develop or nav bar) :O! . A rebase was considered, but a pull request is needed for that. In this regard, it was decided to apply upcoming changes in the navbar-component branch, stash the changes, and once the improvement is implemented, find the best way to resolve and apply those changes.

**Comment by Roxha-V** [comment]
Saved working directory and index state on navbar-component branch [stash name: cambios para aplicar en branch 28 - Improvement - navbar menu] where the changes to resolve the issue were implemented.  
Waiting for the pr to be resolved to rebase branch 28, to add the changes implemented in said branch, review them and finally, if successful, merge them. @devPalta
