### ISSUE TITLE
Revision de estructura de proyecto

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#3]
**Este ticket es para evaluar y estimar cambios necesarios del cual surgirán nuevos tickets**

Tratar de aplicar a las ramas actuales de trabajo los cambios pertinentes para lograr

- https://nextjs.org/docs/app/building-your-application/routing/colocation

con el fin de  darle organizacion adecuada a componentes 

por otro lado entendimiento de layout

- https://www.builder.io/blog/layouts-in-nextjs-14-visual
- https://medium.com/@KiranMohan27/enhancing-your-next-js-application-with-custom-layouts-5645b1d58132

**Comment by Roxha-V** [comment]
Se deberia agregar 2 nuevas issues (a ser agregadas a la brevedad).

1- Revision de la implementancion de mejora para el navbar.(mejora realizada, faltaria terminar detalles de estilo y visual)

2- Revision para cambiar la implementacion del hero component para luego revisar sus cambios y finalmente mergearlo al Home.
