### ISSUE TITLE
Contact section validation

### ISSUE THREAD

**Issue by Roxha-V** [Roxha-V/PTGA-Landing#41]

**Comment by devPalter** [comment]
la validacion el formulario estara dada por campos con datos de cualquier tipo, la interaccion implica que sino hay campos sin datos no pueda enviarse el formulario (no se deberia hacer submit sin datos de nombre ni msg), se debera añadir estilos de boton activo o inactivo segun la validacion de ambos campos

**Comment by Roxha-V** [comment]
![photo1717617570](https://github.com/Roxha-V/PTGA-Landing/assets/139147512/c597c09d-bfc1-4083-aa76-96094f8e1903)
![photo1717617570](https://github.com/Roxha-V/PTGA-Landing/assets/139147512/c597c09d-bfc1-4083-aa76-96094f8e1903)
![photo1717617570](https://github.com/Roxha-V/PTGA-Landing/assets/139147512/c597c09d-bfc1-4083-aa76-96094f8e1903)
