### ISSUE TITLE
handle contact phone number with env variables

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#58]

**Comment by Roxha-V** [comment]
making it in test branch

**Comment by devPalter** [comment]
Some articles 

- [Introduction](https://medium.com/chingu/an-introduction-to-environment-variables-and-how-to-use-them-f602f66d15fa)
- [Configure ENV's on NEXTJS](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables)

**Comment by devPalter** [comment]
La idea de usar variables de entornos es conseguir que el valor de número de contacto(para ser usado en wsp) no este escrito literalmente en el codigo, sino que asigne por fuera del codigo.

Evitando en la practica que tenemos para este proyecto tener que hacer un commit y pr para cuando se requiera cambiarlo.

¿Existen algun otro valor que podamos manejar con variable de entorno?
