### ISSUE TITLE
Generar Footter-component 

### ISSUE THREAD

**Issue by Roxha-V** [Roxha-V/PTGA-Landing#6]
Generarlo a modo de crear una estructura personalizada para que este y otros componentes  queden fijos, si es que hay cambios en la pagina ppal.

**Comment by Roxha-V** [comment]
Se crea footer-component en su propia branch, solo su estructura a modo de prueba para organizar el layout de la aplicacion. Se debe editar su estilo y funcionalidad.

**Comment by devPalter** [comment]
cerrado e intergado en pr https://github.com/Roxha-V/PTGA-Landing/pull/8
