### ISSUE TITLE
services - improvements

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#61]
add title section centrado
check cards shadows to work properly on section 
remove section padding

**Comment by luis-mcr** [comment]
Creé la rama e hice los cambios. Espero a cerciorarnos de que hice bien todo el proceso en la rama #52 para proceder con estos.

**Comment by devPalter** [comment]
Buenas @luis-mcr, no hace falta esperar el #52 ya que deberian pensarse como elementos distintos con cierta independencia de que resuelve cada uno. 
Por otro lado al día de hoy la task #52 esta cerrada, pr mergeado y sus cambios integrados en develop  🙌  buen trabajo.
Lo que si se integro en develop otra branch que modifico la seccion de servicios y las cards, por lo que deberias revisar si hay confictos con tus cambios y en caso que lo haya podemos resolverlos conservando un mezcla de ambos.

**Comment by luis-mcr** [comment]
Ey, @devPalta. Anoche justo estuve con eso. Efectivamente surgieron conflictos. Estuve leyendo un ratito como resolver conflictos manualmente y pude avanzar hasta hacer el rebase (aunque perdí alguno de los cambios por el camino 😭). Así que esta mañana los añadí de nuevo e hice el PR.
