### ISSUE TITLE
Add SEO elements

### ISSUE THREAD

**Issue by devPalter** [Roxha-V/PTGA-Landing#78]
we should add:

- [x] page title
- [x] page description
- [x] page favicon
- [x] sections aria-label
- [x] buttons aria-label

- https://nextjs.org/docs/app/building-your-application/optimizing/metadata
- https://web.dev/learn/accessibility/aria-html?continue=https%3A%2F%2Fweb.dev%2Flearn%2Faccessibility%2F%23article-https%3A%2F%2Fweb.dev%2Flearn%2Faccessibility%2Faria-html

- https://bejamas.io/hub/guides/next-js-and-accessibility

**Comment by Roxha-V** [comment]
work in progresss
